############################################################################################
######################################## server ############################################
############################################################################################
server:
  port: 8762
############################################################################################
######################################## spring ############################################
############################################################################################  
spring:
  application:
    name: config-center-server
  cloud:
    config:
      server:
        git:
          # 配置中心仓库地址
          uri: http://192.168.163.41:1180/micro-service/config-center-repo.git
          username: zhechu
          password: 12345678
############################################################################################
######################################## eureka ############################################
############################################################################################
eureka : 
  client : 
     serviceUrl : 
        defaultZone : http://127.0.0.1:8761/eureka
  instance : 
      preferIpAddress : true
      #Renew频率,默认是30秒
      leaseRenewalIntervalInSeconds : 60
      #服务失效时间,默认是90秒
      leaseExpirationDurationInSeconds : 120
      instanceId : ${spring.cloud.client.ipAddress}:${server.port}            
############################################################################################
######################################## hystrix ###########################################
############################################################################################
hystrix : 
   command :
      default : 
          execution :
              timeout:
                    enabled : false